// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/message.proto

package space.marquardt.protobuf;

import com.google.protobuf.AbstractMessageLite;

public final class Demo {
	private Demo() {
	}

	public static void registerAllExtensions(final com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(final com.google.protobuf.ExtensionRegistry registry) {
		Demo.registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
	}

	public interface CourseOrBuilder extends
	// @@protoc_insertion_point(interface_extends:space.marquardt.Course)
	com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>int32 id = 1;</code>
		 */
		int getId();

		/**
		 * <code>string course_name = 2;</code>
		 */
		java.lang.String getCourseName();

		/**
		 * <code>string course_name = 2;</code>
		 */
		com.google.protobuf.ByteString getCourseNameBytes();

		/**
		 * <code>repeated .space.marquardt.Student student = 3;</code>
		 */
		java.util.List<space.marquardt.protobuf.Demo.Student> getStudentList();

		/**
		 * <code>repeated .space.marquardt.Student student = 3;</code>
		 */
		space.marquardt.protobuf.Demo.Student getStudent(int index);

		/**
		 * <code>repeated .space.marquardt.Student student = 3;</code>
		 */
		int getStudentCount();

		/**
		 * <code>repeated .space.marquardt.Student student = 3;</code>
		 */
		java.util.List<? extends space.marquardt.protobuf.Demo.StudentOrBuilder> getStudentOrBuilderList();

		/**
		 * <code>repeated .space.marquardt.Student student = 3;</code>
		 */
		space.marquardt.protobuf.Demo.StudentOrBuilder getStudentOrBuilder(int index);
	}

	/**
	 * Protobuf type {@code space.marquardt.Course}
	 */
	public static final class Course extends com.google.protobuf.GeneratedMessageV3 implements
	// @@protoc_insertion_point(message_implements:space.marquardt.Course)
	CourseOrBuilder {
		// Use Course.newBuilder() to construct.
		private Course(final com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private Course() {
			this.id_ = 0;
			this.courseName_ = "";
			this.student_ = java.util.Collections.emptyList();
		}

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
		}

		private Course(final com.google.protobuf.CodedInputStream input,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			int mutable_bitField0_ = 0;
			try {
				boolean done = false;
				while (!done) {
					final int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!input.skipField(tag)) {
							done = true;
						}
						break;
					}
					case 8: {

						this.id_ = input.readInt32();
						break;
					}
					case 18: {
						final java.lang.String s = input.readStringRequireUtf8();

						this.courseName_ = s;
						break;
					}
					case 26: {
						if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
							this.student_ = new java.util.ArrayList<>();
							mutable_bitField0_ |= 0x00000004;
						}
						this.student_.add(
								input.readMessage(space.marquardt.protobuf.Demo.Student.parser(), extensionRegistry));
						break;
					}
					}
				}
			} catch (final com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (final java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
			} finally {
				if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
					this.student_ = java.util.Collections.unmodifiableList(this.student_);
				}
				this.makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return space.marquardt.protobuf.Demo.internal_static_space_marquardt_Course_descriptor;
		}

		@Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return space.marquardt.protobuf.Demo.internal_static_space_marquardt_Course_fieldAccessorTable
					.ensureFieldAccessorsInitialized(space.marquardt.protobuf.Demo.Course.class,
							space.marquardt.protobuf.Demo.Course.Builder.class);
		}

		private int bitField0_;
		public static final int ID_FIELD_NUMBER = 1;
		private int id_;

		/**
		 * <code>int32 id = 1;</code>
		 */
		@Override
		public int getId() {
			return this.id_;
		}

		public static final int COURSE_NAME_FIELD_NUMBER = 2;
		private volatile java.lang.Object courseName_;

		/**
		 * <code>string course_name = 2;</code>
		 */
		@Override
		public java.lang.String getCourseName() {
			final java.lang.Object ref = this.courseName_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				final com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				final java.lang.String s = bs.toStringUtf8();
				this.courseName_ = s;
				return s;
			}
		}

		/**
		 * <code>string course_name = 2;</code>
		 */
		@Override
		public com.google.protobuf.ByteString getCourseNameBytes() {
			final java.lang.Object ref = this.courseName_;
			if (ref instanceof java.lang.String) {
				final com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((java.lang.String) ref);
				this.courseName_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int STUDENT_FIELD_NUMBER = 3;
		private java.util.List<space.marquardt.protobuf.Demo.Student> student_;

		/**
		 * <code>repeated .space.marquardt.Student student = 3;</code>
		 */
		@Override
		public java.util.List<space.marquardt.protobuf.Demo.Student> getStudentList() {
			return this.student_;
		}

		/**
		 * <code>repeated .space.marquardt.Student student = 3;</code>
		 */
		@Override
		public java.util.List<? extends space.marquardt.protobuf.Demo.StudentOrBuilder> getStudentOrBuilderList() {
			return this.student_;
		}

		/**
		 * <code>repeated .space.marquardt.Student student = 3;</code>
		 */
		@Override
		public int getStudentCount() {
			return this.student_.size();
		}

		/**
		 * <code>repeated .space.marquardt.Student student = 3;</code>
		 */
		@Override
		public space.marquardt.protobuf.Demo.Student getStudent(final int index) {
			return this.student_.get(index);
		}

		/**
		 * <code>repeated .space.marquardt.Student student = 3;</code>
		 */
		@Override
		public space.marquardt.protobuf.Demo.StudentOrBuilder getStudentOrBuilder(final int index) {
			return this.student_.get(index);
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			final byte isInitialized = this.memoizedIsInitialized;
			if (isInitialized == 1) {
				return true;
			}
			if (isInitialized == 0) {
				return false;
			}

			this.memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(final com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			if (this.id_ != 0) {
				output.writeInt32(1, this.id_);
			}
			if (!this.getCourseNameBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 2, this.courseName_);
			}
			for (int i = 0; i < this.student_.size(); i++) {
				output.writeMessage(3, this.student_.get(i));
			}
		}

		@Override
		public int getSerializedSize() {
			int size = this.memoizedSize;
			if (size != -1) {
				return size;
			}

			size = 0;
			if (this.id_ != 0) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, this.id_);
			}
			if (!this.getCourseNameBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, this.courseName_);
			}
			for (int i = 0; i < this.student_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(3, this.student_.get(i));
			}
			this.memoizedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof space.marquardt.protobuf.Demo.Course)) {
				return super.equals(obj);
			}
			final space.marquardt.protobuf.Demo.Course other = (space.marquardt.protobuf.Demo.Course) obj;

			boolean result = true;
			result = result && (this.getId() == other.getId());
			result = result && this.getCourseName().equals(other.getCourseName());
			result = result && this.getStudentList().equals(other.getStudentList());
			return result;
		}

		@java.lang.Override
		public int hashCode() {
			if (this.memoizedHashCode != 0) {
				return this.memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + Course.getDescriptor().hashCode();
			hash = (37 * hash) + Course.ID_FIELD_NUMBER;
			hash = (53 * hash) + this.getId();
			hash = (37 * hash) + Course.COURSE_NAME_FIELD_NUMBER;
			hash = (53 * hash) + this.getCourseName().hashCode();
			if (this.getStudentCount() > 0) {
				hash = (37 * hash) + Course.STUDENT_FIELD_NUMBER;
				hash = (53 * hash) + this.getStudentList().hashCode();
			}
			hash = (29 * hash) + this.unknownFields.hashCode();
			this.memoizedHashCode = hash;
			return hash;
		}

		public static space.marquardt.protobuf.Demo.Course parseFrom(final com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return Course.PARSER.parseFrom(data);
		}

		public static space.marquardt.protobuf.Demo.Course parseFrom(final com.google.protobuf.ByteString data,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return Course.PARSER.parseFrom(data, extensionRegistry);
		}

		public static space.marquardt.protobuf.Demo.Course parseFrom(final byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return Course.PARSER.parseFrom(data);
		}

		public static space.marquardt.protobuf.Demo.Course parseFrom(final byte[] data,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return Course.PARSER.parseFrom(data, extensionRegistry);
		}

		public static space.marquardt.protobuf.Demo.Course parseFrom(final java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(Course.PARSER, input);
		}

		public static space.marquardt.protobuf.Demo.Course parseFrom(final java.io.InputStream input,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(Course.PARSER, input, extensionRegistry);
		}

		public static space.marquardt.protobuf.Demo.Course parseDelimitedFrom(final java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(Course.PARSER, input);
		}

		public static space.marquardt.protobuf.Demo.Course parseDelimitedFrom(final java.io.InputStream input,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(Course.PARSER, input,
					extensionRegistry);
		}

		public static space.marquardt.protobuf.Demo.Course parseFrom(final com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(Course.PARSER, input);
		}

		public static space.marquardt.protobuf.Demo.Course parseFrom(final com.google.protobuf.CodedInputStream input,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(Course.PARSER, input, extensionRegistry);
		}

		@Override
		public Builder newBuilderForType() {
			return Course.newBuilder();
		}

		public static Builder newBuilder() {
			return Course.DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(final space.marquardt.protobuf.Demo.Course prototype) {
			return Course.DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		@Override
		public Builder toBuilder() {
			return this == Course.DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(final com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			final Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code space.marquardt.Course}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
		// @@protoc_insertion_point(builder_implements:space.marquardt.Course)
		space.marquardt.protobuf.Demo.CourseOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return space.marquardt.protobuf.Demo.internal_static_space_marquardt_Course_descriptor;
			}

			@Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return space.marquardt.protobuf.Demo.internal_static_space_marquardt_Course_fieldAccessorTable
						.ensureFieldAccessorsInitialized(space.marquardt.protobuf.Demo.Course.class,
								space.marquardt.protobuf.Demo.Course.Builder.class);
			}

			// Construct using space.marquardt.protobuf.Demo.Course.newBuilder()
			private Builder() {
				this.maybeForceBuilderInitialization();
			}

			private Builder(final com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				this.maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
					this.getStudentFieldBuilder();
				}
			}

			@Override
			public Builder clear() {
				super.clear();
				this.id_ = 0;

				this.courseName_ = "";

				if (this.studentBuilder_ == null) {
					this.student_ = java.util.Collections.emptyList();
					this.bitField0_ = (this.bitField0_ & ~0x00000004);
				} else {
					this.studentBuilder_.clear();
				}
				return this;
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return space.marquardt.protobuf.Demo.internal_static_space_marquardt_Course_descriptor;
			}

			@Override
			public space.marquardt.protobuf.Demo.Course getDefaultInstanceForType() {
				return space.marquardt.protobuf.Demo.Course.getDefaultInstance();
			}

			@Override
			public space.marquardt.protobuf.Demo.Course build() {
				final space.marquardt.protobuf.Demo.Course result = this.buildPartial();
				if (!result.isInitialized()) {
					throw com.google.protobuf.AbstractMessage.Builder.newUninitializedMessageException(result);
				}
				return result;
			}

			@Override
			public space.marquardt.protobuf.Demo.Course buildPartial() {
				final space.marquardt.protobuf.Demo.Course result = new space.marquardt.protobuf.Demo.Course(this);
				final int from_bitField0_ = this.bitField0_;
				final int to_bitField0_ = 0;
				result.id_ = this.id_;
				result.courseName_ = this.courseName_;
				if (this.studentBuilder_ == null) {
					if (((this.bitField0_ & 0x00000004) == 0x00000004)) {
						this.student_ = java.util.Collections.unmodifiableList(this.student_);
						this.bitField0_ = (this.bitField0_ & ~0x00000004);
					}
					result.student_ = this.student_;
				} else {
					result.student_ = this.studentBuilder_.build();
				}
				result.bitField0_ = to_bitField0_;
				this.onBuilt();
				return result;
			}

			@Override
			public Builder clone() {
				return super.clone();
			}

			@Override
			public Builder setField(final com.google.protobuf.Descriptors.FieldDescriptor field, final Object value) {
				return super.setField(field, value);
			}

			@Override
			public Builder clearField(final com.google.protobuf.Descriptors.FieldDescriptor field) {
				return super.clearField(field);
			}

			@Override
			public Builder clearOneof(final com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return super.clearOneof(oneof);
			}

			@Override
			public Builder setRepeatedField(final com.google.protobuf.Descriptors.FieldDescriptor field,
					final int index, final Object value) {
				return super.setRepeatedField(field, index, value);
			}

			@Override
			public Builder addRepeatedField(final com.google.protobuf.Descriptors.FieldDescriptor field,
					final Object value) {
				return super.addRepeatedField(field, value);
			}

			@Override
			public Builder mergeFrom(final com.google.protobuf.Message other) {
				if (other instanceof space.marquardt.protobuf.Demo.Course) {
					return this.mergeFrom((space.marquardt.protobuf.Demo.Course) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(final space.marquardt.protobuf.Demo.Course other) {
				if (other == space.marquardt.protobuf.Demo.Course.getDefaultInstance()) {
					return this;
				}
				if (other.getId() != 0) {
					this.setId(other.getId());
				}
				if (!other.getCourseName().isEmpty()) {
					this.courseName_ = other.courseName_;
					this.onChanged();
				}
				if (this.studentBuilder_ == null) {
					if (!other.student_.isEmpty()) {
						if (this.student_.isEmpty()) {
							this.student_ = other.student_;
							this.bitField0_ = (this.bitField0_ & ~0x00000004);
						} else {
							this.ensureStudentIsMutable();
							this.student_.addAll(other.student_);
						}
						this.onChanged();
					}
				} else {
					if (!other.student_.isEmpty()) {
						if (this.studentBuilder_.isEmpty()) {
							this.studentBuilder_.dispose();
							this.studentBuilder_ = null;
							this.student_ = other.student_;
							this.bitField0_ = (this.bitField0_ & ~0x00000004);
							this.studentBuilder_ = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
									? this.getStudentFieldBuilder() : null;
						} else {
							this.studentBuilder_.addAllMessages(other.student_);
						}
					}
				}
				this.onChanged();
				return this;
			}

			@Override
			public final boolean isInitialized() {
				return true;
			}

			@Override
			public Builder mergeFrom(final com.google.protobuf.CodedInputStream input,
					final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				space.marquardt.protobuf.Demo.Course parsedMessage = null;
				try {
					parsedMessage = Course.PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (final com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (space.marquardt.protobuf.Demo.Course) e.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if (parsedMessage != null) {
						this.mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			private int id_;

			/**
			 * <code>int32 id = 1;</code>
			 */
			@Override
			public int getId() {
				return this.id_;
			}

			/**
			 * <code>int32 id = 1;</code>
			 */
			public Builder setId(final int value) {

				this.id_ = value;
				this.onChanged();
				return this;
			}

			/**
			 * <code>int32 id = 1;</code>
			 */
			public Builder clearId() {

				this.id_ = 0;
				this.onChanged();
				return this;
			}

			private java.lang.Object courseName_ = "";

			/**
			 * <code>string course_name = 2;</code>
			 */
			@Override
			public java.lang.String getCourseName() {
				final java.lang.Object ref = this.courseName_;
				if (!(ref instanceof java.lang.String)) {
					final com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					final java.lang.String s = bs.toStringUtf8();
					this.courseName_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string course_name = 2;</code>
			 */
			@Override
			public com.google.protobuf.ByteString getCourseNameBytes() {
				final java.lang.Object ref = this.courseName_;
				if (ref instanceof String) {
					final com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					this.courseName_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string course_name = 2;</code>
			 */
			public Builder setCourseName(final java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				this.courseName_ = value;
				this.onChanged();
				return this;
			}

			/**
			 * <code>string course_name = 2;</code>
			 */
			public Builder clearCourseName() {

				this.courseName_ = Course.getDefaultInstance().getCourseName();
				this.onChanged();
				return this;
			}

			/**
			 * <code>string course_name = 2;</code>
			 */
			public Builder setCourseNameBytes(final com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				AbstractMessageLite.checkByteStringIsUtf8(value);

				this.courseName_ = value;
				this.onChanged();
				return this;
			}

			private java.util.List<space.marquardt.protobuf.Demo.Student> student_ = java.util.Collections.emptyList();

			private void ensureStudentIsMutable() {
				if (!((this.bitField0_ & 0x00000004) == 0x00000004)) {
					this.student_ = new java.util.ArrayList<>(this.student_);
					this.bitField0_ |= 0x00000004;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilderV3<space.marquardt.protobuf.Demo.Student, space.marquardt.protobuf.Demo.Student.Builder, space.marquardt.protobuf.Demo.StudentOrBuilder> studentBuilder_;

			/**
			 * <code>repeated .space.marquardt.Student student = 3;</code>
			 */
			@Override
			public java.util.List<space.marquardt.protobuf.Demo.Student> getStudentList() {
				if (this.studentBuilder_ == null) {
					return java.util.Collections.unmodifiableList(this.student_);
				} else {
					return this.studentBuilder_.getMessageList();
				}
			}

			/**
			 * <code>repeated .space.marquardt.Student student = 3;</code>
			 */
			@Override
			public int getStudentCount() {
				if (this.studentBuilder_ == null) {
					return this.student_.size();
				} else {
					return this.studentBuilder_.getCount();
				}
			}

			/**
			 * <code>repeated .space.marquardt.Student student = 3;</code>
			 */
			@Override
			public space.marquardt.protobuf.Demo.Student getStudent(final int index) {
				if (this.studentBuilder_ == null) {
					return this.student_.get(index);
				} else {
					return this.studentBuilder_.getMessage(index);
				}
			}

			/**
			 * <code>repeated .space.marquardt.Student student = 3;</code>
			 */
			public Builder setStudent(final int index, final space.marquardt.protobuf.Demo.Student value) {
				if (this.studentBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					this.ensureStudentIsMutable();
					this.student_.set(index, value);
					this.onChanged();
				} else {
					this.studentBuilder_.setMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .space.marquardt.Student student = 3;</code>
			 */
			public Builder setStudent(final int index,
					final space.marquardt.protobuf.Demo.Student.Builder builderForValue) {
				if (this.studentBuilder_ == null) {
					this.ensureStudentIsMutable();
					this.student_.set(index, builderForValue.build());
					this.onChanged();
				} else {
					this.studentBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .space.marquardt.Student student = 3;</code>
			 */
			public Builder addStudent(final space.marquardt.protobuf.Demo.Student value) {
				if (this.studentBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					this.ensureStudentIsMutable();
					this.student_.add(value);
					this.onChanged();
				} else {
					this.studentBuilder_.addMessage(value);
				}
				return this;
			}

			/**
			 * <code>repeated .space.marquardt.Student student = 3;</code>
			 */
			public Builder addStudent(final int index, final space.marquardt.protobuf.Demo.Student value) {
				if (this.studentBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					this.ensureStudentIsMutable();
					this.student_.add(index, value);
					this.onChanged();
				} else {
					this.studentBuilder_.addMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .space.marquardt.Student student = 3;</code>
			 */
			public Builder addStudent(final space.marquardt.protobuf.Demo.Student.Builder builderForValue) {
				if (this.studentBuilder_ == null) {
					this.ensureStudentIsMutable();
					this.student_.add(builderForValue.build());
					this.onChanged();
				} else {
					this.studentBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .space.marquardt.Student student = 3;</code>
			 */
			public Builder addStudent(final int index,
					final space.marquardt.protobuf.Demo.Student.Builder builderForValue) {
				if (this.studentBuilder_ == null) {
					this.ensureStudentIsMutable();
					this.student_.add(index, builderForValue.build());
					this.onChanged();
				} else {
					this.studentBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .space.marquardt.Student student = 3;</code>
			 */
			public Builder addAllStudent(
					final java.lang.Iterable<? extends space.marquardt.protobuf.Demo.Student> values) {
				if (this.studentBuilder_ == null) {
					this.ensureStudentIsMutable();
					com.google.protobuf.AbstractMessageLite.Builder.addAll(values, this.student_);
					this.onChanged();
				} else {
					this.studentBuilder_.addAllMessages(values);
				}
				return this;
			}

			/**
			 * <code>repeated .space.marquardt.Student student = 3;</code>
			 */
			public Builder clearStudent() {
				if (this.studentBuilder_ == null) {
					this.student_ = java.util.Collections.emptyList();
					this.bitField0_ = (this.bitField0_ & ~0x00000004);
					this.onChanged();
				} else {
					this.studentBuilder_.clear();
				}
				return this;
			}

			/**
			 * <code>repeated .space.marquardt.Student student = 3;</code>
			 */
			public Builder removeStudent(final int index) {
				if (this.studentBuilder_ == null) {
					this.ensureStudentIsMutable();
					this.student_.remove(index);
					this.onChanged();
				} else {
					this.studentBuilder_.remove(index);
				}
				return this;
			}

			/**
			 * <code>repeated .space.marquardt.Student student = 3;</code>
			 */
			public space.marquardt.protobuf.Demo.Student.Builder getStudentBuilder(final int index) {
				return this.getStudentFieldBuilder().getBuilder(index);
			}

			/**
			 * <code>repeated .space.marquardt.Student student = 3;</code>
			 */
			@Override
			public space.marquardt.protobuf.Demo.StudentOrBuilder getStudentOrBuilder(final int index) {
				if (this.studentBuilder_ == null) {
					return this.student_.get(index);
				} else {
					return this.studentBuilder_.getMessageOrBuilder(index);
				}
			}

			/**
			 * <code>repeated .space.marquardt.Student student = 3;</code>
			 */
			@Override
			public java.util.List<? extends space.marquardt.protobuf.Demo.StudentOrBuilder> getStudentOrBuilderList() {
				if (this.studentBuilder_ != null) {
					return this.studentBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(this.student_);
				}
			}

			/**
			 * <code>repeated .space.marquardt.Student student = 3;</code>
			 */
			public space.marquardt.protobuf.Demo.Student.Builder addStudentBuilder() {
				return this.getStudentFieldBuilder()
						.addBuilder(space.marquardt.protobuf.Demo.Student.getDefaultInstance());
			}

			/**
			 * <code>repeated .space.marquardt.Student student = 3;</code>
			 */
			public space.marquardt.protobuf.Demo.Student.Builder addStudentBuilder(final int index) {
				return this.getStudentFieldBuilder().addBuilder(index,
						space.marquardt.protobuf.Demo.Student.getDefaultInstance());
			}

			/**
			 * <code>repeated .space.marquardt.Student student = 3;</code>
			 */
			public java.util.List<space.marquardt.protobuf.Demo.Student.Builder> getStudentBuilderList() {
				return this.getStudentFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilderV3<space.marquardt.protobuf.Demo.Student, space.marquardt.protobuf.Demo.Student.Builder, space.marquardt.protobuf.Demo.StudentOrBuilder> getStudentFieldBuilder() {
				if (this.studentBuilder_ == null) {
					this.studentBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<>(this.student_,
							((this.bitField0_ & 0x00000004) == 0x00000004), this.getParentForChildren(),
							this.isClean());
					this.student_ = null;
				}
				return this.studentBuilder_;
			}

			@Override
			public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return this;
			}

			@Override
			public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return this;
			}

			// @@protoc_insertion_point(builder_scope:space.marquardt.Course)
		}

		// @@protoc_insertion_point(class_scope:space.marquardt.Course)
		private static final space.marquardt.protobuf.Demo.Course DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new space.marquardt.protobuf.Demo.Course();
		}

		public static space.marquardt.protobuf.Demo.Course getDefaultInstance() {
			return Course.DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<Course> PARSER = new com.google.protobuf.AbstractParser<Course>() {
			@Override
			public Course parsePartialFrom(final com.google.protobuf.CodedInputStream input,
					final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws com.google.protobuf.InvalidProtocolBufferException {
				return new Course(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<Course> parser() {
			return Course.PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<Course> getParserForType() {
			return Course.PARSER;
		}

		@Override
		public space.marquardt.protobuf.Demo.Course getDefaultInstanceForType() {
			return Course.DEFAULT_INSTANCE;
		}

	}

	public interface StudentOrBuilder extends
	// @@protoc_insertion_point(interface_extends:space.marquardt.Student)
	com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>int32 id = 1;</code>
		 */
		int getId();

		/**
		 * <code>string first_name = 2;</code>
		 */
		java.lang.String getFirstName();

		/**
		 * <code>string first_name = 2;</code>
		 */
		com.google.protobuf.ByteString getFirstNameBytes();

		/**
		 * <code>string last_name = 3;</code>
		 */
		java.lang.String getLastName();

		/**
		 * <code>string last_name = 3;</code>
		 */
		com.google.protobuf.ByteString getLastNameBytes();

		/**
		 * <code>string email = 4;</code>
		 */
		java.lang.String getEmail();

		/**
		 * <code>string email = 4;</code>
		 */
		com.google.protobuf.ByteString getEmailBytes();

		/**
		 * <code>repeated .space.marquardt.Student.PhoneNumber phone = 5;</code>
		 */
		java.util.List<space.marquardt.protobuf.Demo.Student.PhoneNumber> getPhoneList();

		/**
		 * <code>repeated .space.marquardt.Student.PhoneNumber phone = 5;</code>
		 */
		space.marquardt.protobuf.Demo.Student.PhoneNumber getPhone(int index);

		/**
		 * <code>repeated .space.marquardt.Student.PhoneNumber phone = 5;</code>
		 */
		int getPhoneCount();

		/**
		 * <code>repeated .space.marquardt.Student.PhoneNumber phone = 5;</code>
		 */
		java.util.List<? extends space.marquardt.protobuf.Demo.Student.PhoneNumberOrBuilder> getPhoneOrBuilderList();

		/**
		 * <code>repeated .space.marquardt.Student.PhoneNumber phone = 5;</code>
		 */
		space.marquardt.protobuf.Demo.Student.PhoneNumberOrBuilder getPhoneOrBuilder(int index);
	}

	/**
	 * Protobuf type {@code space.marquardt.Student}
	 */
	public static final class Student extends com.google.protobuf.GeneratedMessageV3 implements
	// @@protoc_insertion_point(message_implements:space.marquardt.Student)
	StudentOrBuilder {
		// Use Student.newBuilder() to construct.
		private Student(final com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private Student() {
			this.id_ = 0;
			this.firstName_ = "";
			this.lastName_ = "";
			this.email_ = "";
			this.phone_ = java.util.Collections.emptyList();
		}

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
		}

		private Student(final com.google.protobuf.CodedInputStream input,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			int mutable_bitField0_ = 0;
			try {
				boolean done = false;
				while (!done) {
					final int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!input.skipField(tag)) {
							done = true;
						}
						break;
					}
					case 8: {

						this.id_ = input.readInt32();
						break;
					}
					case 18: {
						final java.lang.String s = input.readStringRequireUtf8();

						this.firstName_ = s;
						break;
					}
					case 26: {
						final java.lang.String s = input.readStringRequireUtf8();

						this.lastName_ = s;
						break;
					}
					case 34: {
						final java.lang.String s = input.readStringRequireUtf8();

						this.email_ = s;
						break;
					}
					case 42: {
						if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
							this.phone_ = new java.util.ArrayList<>();
							mutable_bitField0_ |= 0x00000010;
						}
						this.phone_.add(input.readMessage(space.marquardt.protobuf.Demo.Student.PhoneNumber.parser(),
								extensionRegistry));
						break;
					}
					}
				}
			} catch (final com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (final java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
			} finally {
				if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
					this.phone_ = java.util.Collections.unmodifiableList(this.phone_);
				}
				this.makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return space.marquardt.protobuf.Demo.internal_static_space_marquardt_Student_descriptor;
		}

		@Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return space.marquardt.protobuf.Demo.internal_static_space_marquardt_Student_fieldAccessorTable
					.ensureFieldAccessorsInitialized(space.marquardt.protobuf.Demo.Student.class,
							space.marquardt.protobuf.Demo.Student.Builder.class);
		}

		/**
		 * Protobuf enum {@code space.marquardt.Student.PhoneType}
		 */
		public enum PhoneType implements com.google.protobuf.ProtocolMessageEnum {
			/**
			 * <code>MBILE = 0;</code>
			 */
			MBILE(0),
			/**
			 * <code>LANDLINE = 1;</code>
			 */
			LANDLINE(1), UNRECOGNIZED(-1),;

			/**
			 * <code>MBILE = 0;</code>
			 */
			public static final int MBILE_VALUE = 0;
			/**
			 * <code>LANDLINE = 1;</code>
			 */
			public static final int LANDLINE_VALUE = 1;

			@Override
			public final int getNumber() {
				if (this == UNRECOGNIZED) {
					throw new java.lang.IllegalArgumentException("Can't get the number of an unknown enum value.");
				}
				return this.value;
			}

			/**
			 * @deprecated Use {@link #forNumber(int)} instead.
			 */
			@java.lang.Deprecated
			public static PhoneType valueOf(final int value) {
				return PhoneType.forNumber(value);
			}

			public static PhoneType forNumber(final int value) {
				switch (value) {
				case 0:
					return MBILE;
				case 1:
					return LANDLINE;
				default:
					return null;
				}
			}

			public static com.google.protobuf.Internal.EnumLiteMap<PhoneType> internalGetValueMap() {
				return PhoneType.internalValueMap;
			}

			private static final com.google.protobuf.Internal.EnumLiteMap<PhoneType> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
				@Override
				public PhoneType findValueByNumber(final int number) {
					return PhoneType.forNumber(number);
				}
			};

			@Override
			public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
				return PhoneType.getDescriptor().getValues().get(this.ordinal());
			}

			@Override
			public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
				return PhoneType.getDescriptor();
			}

			public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
				return space.marquardt.protobuf.Demo.Student.getDescriptor().getEnumTypes().get(0);
			}

			private static final PhoneType[] VALUES = PhoneType.values();

			public static PhoneType valueOf(final com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
				if (desc.getType() != PhoneType.getDescriptor()) {
					throw new java.lang.IllegalArgumentException("EnumValueDescriptor is not for this type.");
				}
				if (desc.getIndex() == -1) {
					return UNRECOGNIZED;
				}
				return PhoneType.VALUES[desc.getIndex()];
			}

			private final int value;

			private PhoneType(final int value) {
				this.value = value;
			}

			// @@protoc_insertion_point(enum_scope:space.marquardt.Student.PhoneType)
		}

		public interface PhoneNumberOrBuilder extends
		// @@protoc_insertion_point(interface_extends:space.marquardt.Student.PhoneNumber)
		com.google.protobuf.MessageOrBuilder {

			/**
			 * <code>string number = 1;</code>
			 */
			java.lang.String getNumber();

			/**
			 * <code>string number = 1;</code>
			 */
			com.google.protobuf.ByteString getNumberBytes();

			/**
			 * <code>.space.marquardt.Student.PhoneType type = 2;</code>
			 */
			int getTypeValue();

			/**
			 * <code>.space.marquardt.Student.PhoneType type = 2;</code>
			 */
			space.marquardt.protobuf.Demo.Student.PhoneType getType();
		}

		/**
		 * Protobuf type {@code space.marquardt.Student.PhoneNumber}
		 */
		public static final class PhoneNumber extends com.google.protobuf.GeneratedMessageV3 implements
		// @@protoc_insertion_point(message_implements:space.marquardt.Student.PhoneNumber)
		PhoneNumberOrBuilder {
			// Use PhoneNumber.newBuilder() to construct.
			private PhoneNumber(final com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
				super(builder);
			}

			private PhoneNumber() {
				this.number_ = "";
				this.type_ = 0;
			}

			@java.lang.Override
			public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
				return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
			}

			private PhoneNumber(final com.google.protobuf.CodedInputStream input,
					final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws com.google.protobuf.InvalidProtocolBufferException {
				this();
				final int mutable_bitField0_ = 0;
				try {
					boolean done = false;
					while (!done) {
						final int tag = input.readTag();
						switch (tag) {
						case 0:
							done = true;
							break;
						default: {
							if (!input.skipField(tag)) {
								done = true;
							}
							break;
						}
						case 10: {
							final java.lang.String s = input.readStringRequireUtf8();

							this.number_ = s;
							break;
						}
						case 16: {
							final int rawValue = input.readEnum();

							this.type_ = rawValue;
							break;
						}
						}
					}
				} catch (final com.google.protobuf.InvalidProtocolBufferException e) {
					throw e.setUnfinishedMessage(this);
				} catch (final java.io.IOException e) {
					throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
				} finally {
					this.makeExtensionsImmutable();
				}
			}

			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return space.marquardt.protobuf.Demo.internal_static_space_marquardt_Student_PhoneNumber_descriptor;
			}

			@Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return space.marquardt.protobuf.Demo.internal_static_space_marquardt_Student_PhoneNumber_fieldAccessorTable
						.ensureFieldAccessorsInitialized(space.marquardt.protobuf.Demo.Student.PhoneNumber.class,
								space.marquardt.protobuf.Demo.Student.PhoneNumber.Builder.class);
			}

			public static final int NUMBER_FIELD_NUMBER = 1;
			private volatile java.lang.Object number_;

			/**
			 * <code>string number = 1;</code>
			 */
			@Override
			public java.lang.String getNumber() {
				final java.lang.Object ref = this.number_;
				if (ref instanceof java.lang.String) {
					return (java.lang.String) ref;
				} else {
					final com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					final java.lang.String s = bs.toStringUtf8();
					this.number_ = s;
					return s;
				}
			}

			/**
			 * <code>string number = 1;</code>
			 */
			@Override
			public com.google.protobuf.ByteString getNumberBytes() {
				final java.lang.Object ref = this.number_;
				if (ref instanceof java.lang.String) {
					final com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					this.number_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			public static final int TYPE_FIELD_NUMBER = 2;
			private int type_;

			/**
			 * <code>.space.marquardt.Student.PhoneType type = 2;</code>
			 */
			@Override
			public int getTypeValue() {
				return this.type_;
			}

			/**
			 * <code>.space.marquardt.Student.PhoneType type = 2;</code>
			 */
			@Override
			public space.marquardt.protobuf.Demo.Student.PhoneType getType() {
				final space.marquardt.protobuf.Demo.Student.PhoneType result = space.marquardt.protobuf.Demo.Student.PhoneType
						.valueOf(this.type_);
				return result == null ? space.marquardt.protobuf.Demo.Student.PhoneType.UNRECOGNIZED : result;
			}

			private byte memoizedIsInitialized = -1;

			@Override
			public final boolean isInitialized() {
				final byte isInitialized = this.memoizedIsInitialized;
				if (isInitialized == 1) {
					return true;
				}
				if (isInitialized == 0) {
					return false;
				}

				this.memoizedIsInitialized = 1;
				return true;
			}

			@Override
			public void writeTo(final com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
				if (!this.getNumberBytes().isEmpty()) {
					com.google.protobuf.GeneratedMessageV3.writeString(output, 1, this.number_);
				}
				if (this.type_ != space.marquardt.protobuf.Demo.Student.PhoneType.MBILE.getNumber()) {
					output.writeEnum(2, this.type_);
				}
			}

			@Override
			public int getSerializedSize() {
				int size = this.memoizedSize;
				if (size != -1) {
					return size;
				}

				size = 0;
				if (!this.getNumberBytes().isEmpty()) {
					size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, this.number_);
				}
				if (this.type_ != space.marquardt.protobuf.Demo.Student.PhoneType.MBILE.getNumber()) {
					size += com.google.protobuf.CodedOutputStream.computeEnumSize(2, this.type_);
				}
				this.memoizedSize = size;
				return size;
			}

			private static final long serialVersionUID = 0L;

			@java.lang.Override
			public boolean equals(final java.lang.Object obj) {
				if (obj == this) {
					return true;
				}
				if (!(obj instanceof space.marquardt.protobuf.Demo.Student.PhoneNumber)) {
					return super.equals(obj);
				}
				final space.marquardt.protobuf.Demo.Student.PhoneNumber other = (space.marquardt.protobuf.Demo.Student.PhoneNumber) obj;

				boolean result = true;
				result = result && this.getNumber().equals(other.getNumber());
				result = result && this.type_ == other.type_;
				return result;
			}

			@java.lang.Override
			public int hashCode() {
				if (this.memoizedHashCode != 0) {
					return this.memoizedHashCode;
				}
				int hash = 41;
				hash = (19 * hash) + PhoneNumber.getDescriptor().hashCode();
				hash = (37 * hash) + PhoneNumber.NUMBER_FIELD_NUMBER;
				hash = (53 * hash) + this.getNumber().hashCode();
				hash = (37 * hash) + PhoneNumber.TYPE_FIELD_NUMBER;
				hash = (53 * hash) + this.type_;
				hash = (29 * hash) + this.unknownFields.hashCode();
				this.memoizedHashCode = hash;
				return hash;
			}

			public static space.marquardt.protobuf.Demo.Student.PhoneNumber parseFrom(
					final com.google.protobuf.ByteString data)
							throws com.google.protobuf.InvalidProtocolBufferException {
				return PhoneNumber.PARSER.parseFrom(data);
			}

			public static space.marquardt.protobuf.Demo.Student.PhoneNumber parseFrom(
					final com.google.protobuf.ByteString data,
					final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws com.google.protobuf.InvalidProtocolBufferException {
				return PhoneNumber.PARSER.parseFrom(data, extensionRegistry);
			}

			public static space.marquardt.protobuf.Demo.Student.PhoneNumber parseFrom(final byte[] data)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return PhoneNumber.PARSER.parseFrom(data);
			}

			public static space.marquardt.protobuf.Demo.Student.PhoneNumber parseFrom(final byte[] data,
					final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws com.google.protobuf.InvalidProtocolBufferException {
				return PhoneNumber.PARSER.parseFrom(data, extensionRegistry);
			}

			public static space.marquardt.protobuf.Demo.Student.PhoneNumber parseFrom(final java.io.InputStream input)
					throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PhoneNumber.PARSER, input);
			}

			public static space.marquardt.protobuf.Demo.Student.PhoneNumber parseFrom(final java.io.InputStream input,
					final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PhoneNumber.PARSER, input,
						extensionRegistry);
			}

			public static space.marquardt.protobuf.Demo.Student.PhoneNumber parseDelimitedFrom(
					final java.io.InputStream input) throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PhoneNumber.PARSER, input);
			}

			public static space.marquardt.protobuf.Demo.Student.PhoneNumber parseDelimitedFrom(
					final java.io.InputStream input, final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PhoneNumber.PARSER, input,
						extensionRegistry);
			}

			public static space.marquardt.protobuf.Demo.Student.PhoneNumber parseFrom(
					final com.google.protobuf.CodedInputStream input) throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PhoneNumber.PARSER, input);
			}

			public static space.marquardt.protobuf.Demo.Student.PhoneNumber parseFrom(
					final com.google.protobuf.CodedInputStream input,
					final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PhoneNumber.PARSER, input,
						extensionRegistry);
			}

			@Override
			public Builder newBuilderForType() {
				return PhoneNumber.newBuilder();
			}

			public static Builder newBuilder() {
				return PhoneNumber.DEFAULT_INSTANCE.toBuilder();
			}

			public static Builder newBuilder(final space.marquardt.protobuf.Demo.Student.PhoneNumber prototype) {
				return PhoneNumber.DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
			}

			@Override
			public Builder toBuilder() {
				return this == PhoneNumber.DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
			}

			@java.lang.Override
			protected Builder newBuilderForType(final com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				final Builder builder = new Builder(parent);
				return builder;
			}

			/**
			 * Protobuf type {@code space.marquardt.Student.PhoneNumber}
			 */
			public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
			// @@protoc_insertion_point(builder_implements:space.marquardt.Student.PhoneNumber)
			space.marquardt.protobuf.Demo.Student.PhoneNumberOrBuilder {
				public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
					return space.marquardt.protobuf.Demo.internal_static_space_marquardt_Student_PhoneNumber_descriptor;
				}

				@Override
				protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
					return space.marquardt.protobuf.Demo.internal_static_space_marquardt_Student_PhoneNumber_fieldAccessorTable
							.ensureFieldAccessorsInitialized(space.marquardt.protobuf.Demo.Student.PhoneNumber.class,
									space.marquardt.protobuf.Demo.Student.PhoneNumber.Builder.class);
				}

				// Construct using
				// space.marquardt.protobuf.Demo.Student.PhoneNumber.newBuilder()
				private Builder() {
					this.maybeForceBuilderInitialization();
				}

				private Builder(final com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
					super(parent);
					this.maybeForceBuilderInitialization();
				}

				private void maybeForceBuilderInitialization() {
					if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
					}
				}

				@Override
				public Builder clear() {
					super.clear();
					this.number_ = "";

					this.type_ = 0;

					return this;
				}

				@Override
				public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
					return space.marquardt.protobuf.Demo.internal_static_space_marquardt_Student_PhoneNumber_descriptor;
				}

				@Override
				public space.marquardt.protobuf.Demo.Student.PhoneNumber getDefaultInstanceForType() {
					return space.marquardt.protobuf.Demo.Student.PhoneNumber.getDefaultInstance();
				}

				@Override
				public space.marquardt.protobuf.Demo.Student.PhoneNumber build() {
					final space.marquardt.protobuf.Demo.Student.PhoneNumber result = this.buildPartial();
					if (!result.isInitialized()) {
						throw com.google.protobuf.AbstractMessage.Builder.newUninitializedMessageException(result);
					}
					return result;
				}

				@Override
				public space.marquardt.protobuf.Demo.Student.PhoneNumber buildPartial() {
					final space.marquardt.protobuf.Demo.Student.PhoneNumber result = new space.marquardt.protobuf.Demo.Student.PhoneNumber(
							this);
					result.number_ = this.number_;
					result.type_ = this.type_;
					this.onBuilt();
					return result;
				}

				@Override
				public Builder clone() {
					return super.clone();
				}

				@Override
				public Builder setField(final com.google.protobuf.Descriptors.FieldDescriptor field,
						final Object value) {
					return super.setField(field, value);
				}

				@Override
				public Builder clearField(final com.google.protobuf.Descriptors.FieldDescriptor field) {
					return super.clearField(field);
				}

				@Override
				public Builder clearOneof(final com.google.protobuf.Descriptors.OneofDescriptor oneof) {
					return super.clearOneof(oneof);
				}

				@Override
				public Builder setRepeatedField(final com.google.protobuf.Descriptors.FieldDescriptor field,
						final int index, final Object value) {
					return super.setRepeatedField(field, index, value);
				}

				@Override
				public Builder addRepeatedField(final com.google.protobuf.Descriptors.FieldDescriptor field,
						final Object value) {
					return super.addRepeatedField(field, value);
				}

				@Override
				public Builder mergeFrom(final com.google.protobuf.Message other) {
					if (other instanceof space.marquardt.protobuf.Demo.Student.PhoneNumber) {
						return this.mergeFrom((space.marquardt.protobuf.Demo.Student.PhoneNumber) other);
					} else {
						super.mergeFrom(other);
						return this;
					}
				}

				public Builder mergeFrom(final space.marquardt.protobuf.Demo.Student.PhoneNumber other) {
					if (other == space.marquardt.protobuf.Demo.Student.PhoneNumber.getDefaultInstance()) {
						return this;
					}
					if (!other.getNumber().isEmpty()) {
						this.number_ = other.number_;
						this.onChanged();
					}
					if (other.type_ != 0) {
						this.setTypeValue(other.getTypeValue());
					}
					this.onChanged();
					return this;
				}

				@Override
				public final boolean isInitialized() {
					return true;
				}

				@Override
				public Builder mergeFrom(final com.google.protobuf.CodedInputStream input,
						final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
					space.marquardt.protobuf.Demo.Student.PhoneNumber parsedMessage = null;
					try {
						parsedMessage = PhoneNumber.PARSER.parsePartialFrom(input, extensionRegistry);
					} catch (final com.google.protobuf.InvalidProtocolBufferException e) {
						parsedMessage = (space.marquardt.protobuf.Demo.Student.PhoneNumber) e.getUnfinishedMessage();
						throw e.unwrapIOException();
					} finally {
						if (parsedMessage != null) {
							this.mergeFrom(parsedMessage);
						}
					}
					return this;
				}

				private java.lang.Object number_ = "";

				/**
				 * <code>string number = 1;</code>
				 */
				@Override
				public java.lang.String getNumber() {
					final java.lang.Object ref = this.number_;
					if (!(ref instanceof java.lang.String)) {
						final com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
						final java.lang.String s = bs.toStringUtf8();
						this.number_ = s;
						return s;
					} else {
						return (java.lang.String) ref;
					}
				}

				/**
				 * <code>string number = 1;</code>
				 */
				@Override
				public com.google.protobuf.ByteString getNumberBytes() {
					final java.lang.Object ref = this.number_;
					if (ref instanceof String) {
						final com.google.protobuf.ByteString b = com.google.protobuf.ByteString
								.copyFromUtf8((java.lang.String) ref);
						this.number_ = b;
						return b;
					} else {
						return (com.google.protobuf.ByteString) ref;
					}
				}

				/**
				 * <code>string number = 1;</code>
				 */
				public Builder setNumber(final java.lang.String value) {
					if (value == null) {
						throw new NullPointerException();
					}

					this.number_ = value;
					this.onChanged();
					return this;
				}

				/**
				 * <code>string number = 1;</code>
				 */
				public Builder clearNumber() {

					this.number_ = PhoneNumber.getDefaultInstance().getNumber();
					this.onChanged();
					return this;
				}

				/**
				 * <code>string number = 1;</code>
				 */
				public Builder setNumberBytes(final com.google.protobuf.ByteString value) {
					if (value == null) {
						throw new NullPointerException();
					}
					AbstractMessageLite.checkByteStringIsUtf8(value);

					this.number_ = value;
					this.onChanged();
					return this;
				}

				private int type_ = 0;

				/**
				 * <code>.space.marquardt.Student.PhoneType type = 2;</code>
				 */
				@Override
				public int getTypeValue() {
					return this.type_;
				}

				/**
				 * <code>.space.marquardt.Student.PhoneType type = 2;</code>
				 */
				public Builder setTypeValue(final int value) {
					this.type_ = value;
					this.onChanged();
					return this;
				}

				/**
				 * <code>.space.marquardt.Student.PhoneType type = 2;</code>
				 */
				@Override
				public space.marquardt.protobuf.Demo.Student.PhoneType getType() {
					final space.marquardt.protobuf.Demo.Student.PhoneType result = space.marquardt.protobuf.Demo.Student.PhoneType
							.valueOf(this.type_);
					return result == null ? space.marquardt.protobuf.Demo.Student.PhoneType.UNRECOGNIZED : result;
				}

				/**
				 * <code>.space.marquardt.Student.PhoneType type = 2;</code>
				 */
				public Builder setType(final space.marquardt.protobuf.Demo.Student.PhoneType value) {
					if (value == null) {
						throw new NullPointerException();
					}

					this.type_ = value.getNumber();
					this.onChanged();
					return this;
				}

				/**
				 * <code>.space.marquardt.Student.PhoneType type = 2;</code>
				 */
				public Builder clearType() {

					this.type_ = 0;
					this.onChanged();
					return this;
				}

				@Override
				public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
					return this;
				}

				@Override
				public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
					return this;
				}

				// @@protoc_insertion_point(builder_scope:space.marquardt.Student.PhoneNumber)
			}

			// @@protoc_insertion_point(class_scope:space.marquardt.Student.PhoneNumber)
			private static final space.marquardt.protobuf.Demo.Student.PhoneNumber DEFAULT_INSTANCE;
			static {
				DEFAULT_INSTANCE = new space.marquardt.protobuf.Demo.Student.PhoneNumber();
			}

			public static space.marquardt.protobuf.Demo.Student.PhoneNumber getDefaultInstance() {
				return PhoneNumber.DEFAULT_INSTANCE;
			}

			private static final com.google.protobuf.Parser<PhoneNumber> PARSER = new com.google.protobuf.AbstractParser<PhoneNumber>() {
				@Override
				public PhoneNumber parsePartialFrom(final com.google.protobuf.CodedInputStream input,
						final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
								throws com.google.protobuf.InvalidProtocolBufferException {
					return new PhoneNumber(input, extensionRegistry);
				}
			};

			public static com.google.protobuf.Parser<PhoneNumber> parser() {
				return PhoneNumber.PARSER;
			}

			@java.lang.Override
			public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
				return PhoneNumber.PARSER;
			}

			@Override
			public space.marquardt.protobuf.Demo.Student.PhoneNumber getDefaultInstanceForType() {
				return PhoneNumber.DEFAULT_INSTANCE;
			}

		}

		private int bitField0_;
		public static final int ID_FIELD_NUMBER = 1;
		private int id_;

		/**
		 * <code>int32 id = 1;</code>
		 */
		@Override
		public int getId() {
			return this.id_;
		}

		public static final int FIRST_NAME_FIELD_NUMBER = 2;
		private volatile java.lang.Object firstName_;

		/**
		 * <code>string first_name = 2;</code>
		 */
		@Override
		public java.lang.String getFirstName() {
			final java.lang.Object ref = this.firstName_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				final com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				final java.lang.String s = bs.toStringUtf8();
				this.firstName_ = s;
				return s;
			}
		}

		/**
		 * <code>string first_name = 2;</code>
		 */
		@Override
		public com.google.protobuf.ByteString getFirstNameBytes() {
			final java.lang.Object ref = this.firstName_;
			if (ref instanceof java.lang.String) {
				final com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((java.lang.String) ref);
				this.firstName_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int LAST_NAME_FIELD_NUMBER = 3;
		private volatile java.lang.Object lastName_;

		/**
		 * <code>string last_name = 3;</code>
		 */
		@Override
		public java.lang.String getLastName() {
			final java.lang.Object ref = this.lastName_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				final com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				final java.lang.String s = bs.toStringUtf8();
				this.lastName_ = s;
				return s;
			}
		}

		/**
		 * <code>string last_name = 3;</code>
		 */
		@Override
		public com.google.protobuf.ByteString getLastNameBytes() {
			final java.lang.Object ref = this.lastName_;
			if (ref instanceof java.lang.String) {
				final com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((java.lang.String) ref);
				this.lastName_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int EMAIL_FIELD_NUMBER = 4;
		private volatile java.lang.Object email_;

		/**
		 * <code>string email = 4;</code>
		 */
		@Override
		public java.lang.String getEmail() {
			final java.lang.Object ref = this.email_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				final com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				final java.lang.String s = bs.toStringUtf8();
				this.email_ = s;
				return s;
			}
		}

		/**
		 * <code>string email = 4;</code>
		 */
		@Override
		public com.google.protobuf.ByteString getEmailBytes() {
			final java.lang.Object ref = this.email_;
			if (ref instanceof java.lang.String) {
				final com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((java.lang.String) ref);
				this.email_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int PHONE_FIELD_NUMBER = 5;
		private java.util.List<space.marquardt.protobuf.Demo.Student.PhoneNumber> phone_;

		/**
		 * <code>repeated .space.marquardt.Student.PhoneNumber phone = 5;</code>
		 */
		@Override
		public java.util.List<space.marquardt.protobuf.Demo.Student.PhoneNumber> getPhoneList() {
			return this.phone_;
		}

		/**
		 * <code>repeated .space.marquardt.Student.PhoneNumber phone = 5;</code>
		 */
		@Override
		public java.util.List<? extends space.marquardt.protobuf.Demo.Student.PhoneNumberOrBuilder> getPhoneOrBuilderList() {
			return this.phone_;
		}

		/**
		 * <code>repeated .space.marquardt.Student.PhoneNumber phone = 5;</code>
		 */
		@Override
		public int getPhoneCount() {
			return this.phone_.size();
		}

		/**
		 * <code>repeated .space.marquardt.Student.PhoneNumber phone = 5;</code>
		 */
		@Override
		public space.marquardt.protobuf.Demo.Student.PhoneNumber getPhone(final int index) {
			return this.phone_.get(index);
		}

		/**
		 * <code>repeated .space.marquardt.Student.PhoneNumber phone = 5;</code>
		 */
		@Override
		public space.marquardt.protobuf.Demo.Student.PhoneNumberOrBuilder getPhoneOrBuilder(final int index) {
			return this.phone_.get(index);
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			final byte isInitialized = this.memoizedIsInitialized;
			if (isInitialized == 1) {
				return true;
			}
			if (isInitialized == 0) {
				return false;
			}

			this.memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(final com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			if (this.id_ != 0) {
				output.writeInt32(1, this.id_);
			}
			if (!this.getFirstNameBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 2, this.firstName_);
			}
			if (!this.getLastNameBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 3, this.lastName_);
			}
			if (!this.getEmailBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 4, this.email_);
			}
			for (int i = 0; i < this.phone_.size(); i++) {
				output.writeMessage(5, this.phone_.get(i));
			}
		}

		@Override
		public int getSerializedSize() {
			int size = this.memoizedSize;
			if (size != -1) {
				return size;
			}

			size = 0;
			if (this.id_ != 0) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, this.id_);
			}
			if (!this.getFirstNameBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, this.firstName_);
			}
			if (!this.getLastNameBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, this.lastName_);
			}
			if (!this.getEmailBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, this.email_);
			}
			for (int i = 0; i < this.phone_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream.computeMessageSize(5, this.phone_.get(i));
			}
			this.memoizedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof space.marquardt.protobuf.Demo.Student)) {
				return super.equals(obj);
			}
			final space.marquardt.protobuf.Demo.Student other = (space.marquardt.protobuf.Demo.Student) obj;

			boolean result = true;
			result = result && (this.getId() == other.getId());
			result = result && this.getFirstName().equals(other.getFirstName());
			result = result && this.getLastName().equals(other.getLastName());
			result = result && this.getEmail().equals(other.getEmail());
			result = result && this.getPhoneList().equals(other.getPhoneList());
			return result;
		}

		@java.lang.Override
		public int hashCode() {
			if (this.memoizedHashCode != 0) {
				return this.memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + Student.getDescriptor().hashCode();
			hash = (37 * hash) + Student.ID_FIELD_NUMBER;
			hash = (53 * hash) + this.getId();
			hash = (37 * hash) + Student.FIRST_NAME_FIELD_NUMBER;
			hash = (53 * hash) + this.getFirstName().hashCode();
			hash = (37 * hash) + Student.LAST_NAME_FIELD_NUMBER;
			hash = (53 * hash) + this.getLastName().hashCode();
			hash = (37 * hash) + Student.EMAIL_FIELD_NUMBER;
			hash = (53 * hash) + this.getEmail().hashCode();
			if (this.getPhoneCount() > 0) {
				hash = (37 * hash) + Student.PHONE_FIELD_NUMBER;
				hash = (53 * hash) + this.getPhoneList().hashCode();
			}
			hash = (29 * hash) + this.unknownFields.hashCode();
			this.memoizedHashCode = hash;
			return hash;
		}

		public static space.marquardt.protobuf.Demo.Student parseFrom(final com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return Student.PARSER.parseFrom(data);
		}

		public static space.marquardt.protobuf.Demo.Student parseFrom(final com.google.protobuf.ByteString data,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return Student.PARSER.parseFrom(data, extensionRegistry);
		}

		public static space.marquardt.protobuf.Demo.Student parseFrom(final byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return Student.PARSER.parseFrom(data);
		}

		public static space.marquardt.protobuf.Demo.Student parseFrom(final byte[] data,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
						throws com.google.protobuf.InvalidProtocolBufferException {
			return Student.PARSER.parseFrom(data, extensionRegistry);
		}

		public static space.marquardt.protobuf.Demo.Student parseFrom(final java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(Student.PARSER, input);
		}

		public static space.marquardt.protobuf.Demo.Student parseFrom(final java.io.InputStream input,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(Student.PARSER, input,
					extensionRegistry);
		}

		public static space.marquardt.protobuf.Demo.Student parseDelimitedFrom(final java.io.InputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(Student.PARSER, input);
		}

		public static space.marquardt.protobuf.Demo.Student parseDelimitedFrom(final java.io.InputStream input,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(Student.PARSER, input,
					extensionRegistry);
		}

		public static space.marquardt.protobuf.Demo.Student parseFrom(final com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(Student.PARSER, input);
		}

		public static space.marquardt.protobuf.Demo.Student parseFrom(final com.google.protobuf.CodedInputStream input,
				final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(Student.PARSER, input,
					extensionRegistry);
		}

		@Override
		public Builder newBuilderForType() {
			return Student.newBuilder();
		}

		public static Builder newBuilder() {
			return Student.DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(final space.marquardt.protobuf.Demo.Student prototype) {
			return Student.DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		@Override
		public Builder toBuilder() {
			return this == Student.DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(final com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			final Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code space.marquardt.Student}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
		// @@protoc_insertion_point(builder_implements:space.marquardt.Student)
		space.marquardt.protobuf.Demo.StudentOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return space.marquardt.protobuf.Demo.internal_static_space_marquardt_Student_descriptor;
			}

			@Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return space.marquardt.protobuf.Demo.internal_static_space_marquardt_Student_fieldAccessorTable
						.ensureFieldAccessorsInitialized(space.marquardt.protobuf.Demo.Student.class,
								space.marquardt.protobuf.Demo.Student.Builder.class);
			}

			// Construct using
			// space.marquardt.protobuf.Demo.Student.newBuilder()
			private Builder() {
				this.maybeForceBuilderInitialization();
			}

			private Builder(final com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				this.maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
					this.getPhoneFieldBuilder();
				}
			}

			@Override
			public Builder clear() {
				super.clear();
				this.id_ = 0;

				this.firstName_ = "";

				this.lastName_ = "";

				this.email_ = "";

				if (this.phoneBuilder_ == null) {
					this.phone_ = java.util.Collections.emptyList();
					this.bitField0_ = (this.bitField0_ & ~0x00000010);
				} else {
					this.phoneBuilder_.clear();
				}
				return this;
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return space.marquardt.protobuf.Demo.internal_static_space_marquardt_Student_descriptor;
			}

			@Override
			public space.marquardt.protobuf.Demo.Student getDefaultInstanceForType() {
				return space.marquardt.protobuf.Demo.Student.getDefaultInstance();
			}

			@Override
			public space.marquardt.protobuf.Demo.Student build() {
				final space.marquardt.protobuf.Demo.Student result = this.buildPartial();
				if (!result.isInitialized()) {
					throw com.google.protobuf.AbstractMessage.Builder.newUninitializedMessageException(result);
				}
				return result;
			}

			@Override
			public space.marquardt.protobuf.Demo.Student buildPartial() {
				final space.marquardt.protobuf.Demo.Student result = new space.marquardt.protobuf.Demo.Student(this);
				final int from_bitField0_ = this.bitField0_;
				final int to_bitField0_ = 0;
				result.id_ = this.id_;
				result.firstName_ = this.firstName_;
				result.lastName_ = this.lastName_;
				result.email_ = this.email_;
				if (this.phoneBuilder_ == null) {
					if (((this.bitField0_ & 0x00000010) == 0x00000010)) {
						this.phone_ = java.util.Collections.unmodifiableList(this.phone_);
						this.bitField0_ = (this.bitField0_ & ~0x00000010);
					}
					result.phone_ = this.phone_;
				} else {
					result.phone_ = this.phoneBuilder_.build();
				}
				result.bitField0_ = to_bitField0_;
				this.onBuilt();
				return result;
			}

			@Override
			public Builder clone() {
				return super.clone();
			}

			@Override
			public Builder setField(final com.google.protobuf.Descriptors.FieldDescriptor field, final Object value) {
				return super.setField(field, value);
			}

			@Override
			public Builder clearField(final com.google.protobuf.Descriptors.FieldDescriptor field) {
				return super.clearField(field);
			}

			@Override
			public Builder clearOneof(final com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return super.clearOneof(oneof);
			}

			@Override
			public Builder setRepeatedField(final com.google.protobuf.Descriptors.FieldDescriptor field,
					final int index, final Object value) {
				return super.setRepeatedField(field, index, value);
			}

			@Override
			public Builder addRepeatedField(final com.google.protobuf.Descriptors.FieldDescriptor field,
					final Object value) {
				return super.addRepeatedField(field, value);
			}

			@Override
			public Builder mergeFrom(final com.google.protobuf.Message other) {
				if (other instanceof space.marquardt.protobuf.Demo.Student) {
					return this.mergeFrom((space.marquardt.protobuf.Demo.Student) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(final space.marquardt.protobuf.Demo.Student other) {
				if (other == space.marquardt.protobuf.Demo.Student.getDefaultInstance()) {
					return this;
				}
				if (other.getId() != 0) {
					this.setId(other.getId());
				}
				if (!other.getFirstName().isEmpty()) {
					this.firstName_ = other.firstName_;
					this.onChanged();
				}
				if (!other.getLastName().isEmpty()) {
					this.lastName_ = other.lastName_;
					this.onChanged();
				}
				if (!other.getEmail().isEmpty()) {
					this.email_ = other.email_;
					this.onChanged();
				}
				if (this.phoneBuilder_ == null) {
					if (!other.phone_.isEmpty()) {
						if (this.phone_.isEmpty()) {
							this.phone_ = other.phone_;
							this.bitField0_ = (this.bitField0_ & ~0x00000010);
						} else {
							this.ensurePhoneIsMutable();
							this.phone_.addAll(other.phone_);
						}
						this.onChanged();
					}
				} else {
					if (!other.phone_.isEmpty()) {
						if (this.phoneBuilder_.isEmpty()) {
							this.phoneBuilder_.dispose();
							this.phoneBuilder_ = null;
							this.phone_ = other.phone_;
							this.bitField0_ = (this.bitField0_ & ~0x00000010);
							this.phoneBuilder_ = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
									? this.getPhoneFieldBuilder() : null;
						} else {
							this.phoneBuilder_.addAllMessages(other.phone_);
						}
					}
				}
				this.onChanged();
				return this;
			}

			@Override
			public final boolean isInitialized() {
				return true;
			}

			@Override
			public Builder mergeFrom(final com.google.protobuf.CodedInputStream input,
					final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				space.marquardt.protobuf.Demo.Student parsedMessage = null;
				try {
					parsedMessage = Student.PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (final com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (space.marquardt.protobuf.Demo.Student) e.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if (parsedMessage != null) {
						this.mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			private int id_;

			/**
			 * <code>int32 id = 1;</code>
			 */
			@Override
			public int getId() {
				return this.id_;
			}

			/**
			 * <code>int32 id = 1;</code>
			 */
			public Builder setId(final int value) {

				this.id_ = value;
				this.onChanged();
				return this;
			}

			/**
			 * <code>int32 id = 1;</code>
			 */
			public Builder clearId() {

				this.id_ = 0;
				this.onChanged();
				return this;
			}

			private java.lang.Object firstName_ = "";

			/**
			 * <code>string first_name = 2;</code>
			 */
			@Override
			public java.lang.String getFirstName() {
				final java.lang.Object ref = this.firstName_;
				if (!(ref instanceof java.lang.String)) {
					final com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					final java.lang.String s = bs.toStringUtf8();
					this.firstName_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string first_name = 2;</code>
			 */
			@Override
			public com.google.protobuf.ByteString getFirstNameBytes() {
				final java.lang.Object ref = this.firstName_;
				if (ref instanceof String) {
					final com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					this.firstName_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string first_name = 2;</code>
			 */
			public Builder setFirstName(final java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				this.firstName_ = value;
				this.onChanged();
				return this;
			}

			/**
			 * <code>string first_name = 2;</code>
			 */
			public Builder clearFirstName() {

				this.firstName_ = Student.getDefaultInstance().getFirstName();
				this.onChanged();
				return this;
			}

			/**
			 * <code>string first_name = 2;</code>
			 */
			public Builder setFirstNameBytes(final com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				AbstractMessageLite.checkByteStringIsUtf8(value);

				this.firstName_ = value;
				this.onChanged();
				return this;
			}

			private java.lang.Object lastName_ = "";

			/**
			 * <code>string last_name = 3;</code>
			 */
			@Override
			public java.lang.String getLastName() {
				final java.lang.Object ref = this.lastName_;
				if (!(ref instanceof java.lang.String)) {
					final com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					final java.lang.String s = bs.toStringUtf8();
					this.lastName_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string last_name = 3;</code>
			 */
			@Override
			public com.google.protobuf.ByteString getLastNameBytes() {
				final java.lang.Object ref = this.lastName_;
				if (ref instanceof String) {
					final com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					this.lastName_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string last_name = 3;</code>
			 */
			public Builder setLastName(final java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				this.lastName_ = value;
				this.onChanged();
				return this;
			}

			/**
			 * <code>string last_name = 3;</code>
			 */
			public Builder clearLastName() {

				this.lastName_ = Student.getDefaultInstance().getLastName();
				this.onChanged();
				return this;
			}

			/**
			 * <code>string last_name = 3;</code>
			 */
			public Builder setLastNameBytes(final com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				AbstractMessageLite.checkByteStringIsUtf8(value);

				this.lastName_ = value;
				this.onChanged();
				return this;
			}

			private java.lang.Object email_ = "";

			/**
			 * <code>string email = 4;</code>
			 */
			@Override
			public java.lang.String getEmail() {
				final java.lang.Object ref = this.email_;
				if (!(ref instanceof java.lang.String)) {
					final com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					final java.lang.String s = bs.toStringUtf8();
					this.email_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>string email = 4;</code>
			 */
			@Override
			public com.google.protobuf.ByteString getEmailBytes() {
				final java.lang.Object ref = this.email_;
				if (ref instanceof String) {
					final com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					this.email_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>string email = 4;</code>
			 */
			public Builder setEmail(final java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				this.email_ = value;
				this.onChanged();
				return this;
			}

			/**
			 * <code>string email = 4;</code>
			 */
			public Builder clearEmail() {

				this.email_ = Student.getDefaultInstance().getEmail();
				this.onChanged();
				return this;
			}

			/**
			 * <code>string email = 4;</code>
			 */
			public Builder setEmailBytes(final com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				AbstractMessageLite.checkByteStringIsUtf8(value);

				this.email_ = value;
				this.onChanged();
				return this;
			}

			private java.util.List<space.marquardt.protobuf.Demo.Student.PhoneNumber> phone_ = java.util.Collections
					.emptyList();

			private void ensurePhoneIsMutable() {
				if (!((this.bitField0_ & 0x00000010) == 0x00000010)) {
					this.phone_ = new java.util.ArrayList<>(this.phone_);
					this.bitField0_ |= 0x00000010;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilderV3<space.marquardt.protobuf.Demo.Student.PhoneNumber, space.marquardt.protobuf.Demo.Student.PhoneNumber.Builder, space.marquardt.protobuf.Demo.Student.PhoneNumberOrBuilder> phoneBuilder_;

			/**
			 * <code>repeated .space.marquardt.Student.PhoneNumber phone = 5;</code>
			 */
			@Override
			public java.util.List<space.marquardt.protobuf.Demo.Student.PhoneNumber> getPhoneList() {
				if (this.phoneBuilder_ == null) {
					return java.util.Collections.unmodifiableList(this.phone_);
				} else {
					return this.phoneBuilder_.getMessageList();
				}
			}

			/**
			 * <code>repeated .space.marquardt.Student.PhoneNumber phone = 5;</code>
			 */
			@Override
			public int getPhoneCount() {
				if (this.phoneBuilder_ == null) {
					return this.phone_.size();
				} else {
					return this.phoneBuilder_.getCount();
				}
			}

			/**
			 * <code>repeated .space.marquardt.Student.PhoneNumber phone = 5;</code>
			 */
			@Override
			public space.marquardt.protobuf.Demo.Student.PhoneNumber getPhone(final int index) {
				if (this.phoneBuilder_ == null) {
					return this.phone_.get(index);
				} else {
					return this.phoneBuilder_.getMessage(index);
				}
			}

			/**
			 * <code>repeated .space.marquardt.Student.PhoneNumber phone = 5;</code>
			 */
			public Builder setPhone(final int index, final space.marquardt.protobuf.Demo.Student.PhoneNumber value) {
				if (this.phoneBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					this.ensurePhoneIsMutable();
					this.phone_.set(index, value);
					this.onChanged();
				} else {
					this.phoneBuilder_.setMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .space.marquardt.Student.PhoneNumber phone = 5;</code>
			 */
			public Builder setPhone(final int index,
					final space.marquardt.protobuf.Demo.Student.PhoneNumber.Builder builderForValue) {
				if (this.phoneBuilder_ == null) {
					this.ensurePhoneIsMutable();
					this.phone_.set(index, builderForValue.build());
					this.onChanged();
				} else {
					this.phoneBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .space.marquardt.Student.PhoneNumber phone = 5;</code>
			 */
			public Builder addPhone(final space.marquardt.protobuf.Demo.Student.PhoneNumber value) {
				if (this.phoneBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					this.ensurePhoneIsMutable();
					this.phone_.add(value);
					this.onChanged();
				} else {
					this.phoneBuilder_.addMessage(value);
				}
				return this;
			}

			/**
			 * <code>repeated .space.marquardt.Student.PhoneNumber phone = 5;</code>
			 */
			public Builder addPhone(final int index, final space.marquardt.protobuf.Demo.Student.PhoneNumber value) {
				if (this.phoneBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					this.ensurePhoneIsMutable();
					this.phone_.add(index, value);
					this.onChanged();
				} else {
					this.phoneBuilder_.addMessage(index, value);
				}
				return this;
			}

			/**
			 * <code>repeated .space.marquardt.Student.PhoneNumber phone = 5;</code>
			 */
			public Builder addPhone(final space.marquardt.protobuf.Demo.Student.PhoneNumber.Builder builderForValue) {
				if (this.phoneBuilder_ == null) {
					this.ensurePhoneIsMutable();
					this.phone_.add(builderForValue.build());
					this.onChanged();
				} else {
					this.phoneBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .space.marquardt.Student.PhoneNumber phone = 5;</code>
			 */
			public Builder addPhone(final int index,
					final space.marquardt.protobuf.Demo.Student.PhoneNumber.Builder builderForValue) {
				if (this.phoneBuilder_ == null) {
					this.ensurePhoneIsMutable();
					this.phone_.add(index, builderForValue.build());
					this.onChanged();
				} else {
					this.phoneBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <code>repeated .space.marquardt.Student.PhoneNumber phone = 5;</code>
			 */
			public Builder addAllPhone(
					final java.lang.Iterable<? extends space.marquardt.protobuf.Demo.Student.PhoneNumber> values) {
				if (this.phoneBuilder_ == null) {
					this.ensurePhoneIsMutable();
					com.google.protobuf.AbstractMessageLite.Builder.addAll(values, this.phone_);
					this.onChanged();
				} else {
					this.phoneBuilder_.addAllMessages(values);
				}
				return this;
			}

			/**
			 * <code>repeated .space.marquardt.Student.PhoneNumber phone = 5;</code>
			 */
			public Builder clearPhone() {
				if (this.phoneBuilder_ == null) {
					this.phone_ = java.util.Collections.emptyList();
					this.bitField0_ = (this.bitField0_ & ~0x00000010);
					this.onChanged();
				} else {
					this.phoneBuilder_.clear();
				}
				return this;
			}

			/**
			 * <code>repeated .space.marquardt.Student.PhoneNumber phone = 5;</code>
			 */
			public Builder removePhone(final int index) {
				if (this.phoneBuilder_ == null) {
					this.ensurePhoneIsMutable();
					this.phone_.remove(index);
					this.onChanged();
				} else {
					this.phoneBuilder_.remove(index);
				}
				return this;
			}

			/**
			 * <code>repeated .space.marquardt.Student.PhoneNumber phone = 5;</code>
			 */
			public space.marquardt.protobuf.Demo.Student.PhoneNumber.Builder getPhoneBuilder(final int index) {
				return this.getPhoneFieldBuilder().getBuilder(index);
			}

			/**
			 * <code>repeated .space.marquardt.Student.PhoneNumber phone = 5;</code>
			 */
			@Override
			public space.marquardt.protobuf.Demo.Student.PhoneNumberOrBuilder getPhoneOrBuilder(final int index) {
				if (this.phoneBuilder_ == null) {
					return this.phone_.get(index);
				} else {
					return this.phoneBuilder_.getMessageOrBuilder(index);
				}
			}

			/**
			 * <code>repeated .space.marquardt.Student.PhoneNumber phone = 5;</code>
			 */
			@Override
			public java.util.List<? extends space.marquardt.protobuf.Demo.Student.PhoneNumberOrBuilder> getPhoneOrBuilderList() {
				if (this.phoneBuilder_ != null) {
					return this.phoneBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(this.phone_);
				}
			}

			/**
			 * <code>repeated .space.marquardt.Student.PhoneNumber phone = 5;</code>
			 */
			public space.marquardt.protobuf.Demo.Student.PhoneNumber.Builder addPhoneBuilder() {
				return this.getPhoneFieldBuilder()
						.addBuilder(space.marquardt.protobuf.Demo.Student.PhoneNumber.getDefaultInstance());
			}

			/**
			 * <code>repeated .space.marquardt.Student.PhoneNumber phone = 5;</code>
			 */
			public space.marquardt.protobuf.Demo.Student.PhoneNumber.Builder addPhoneBuilder(final int index) {
				return this.getPhoneFieldBuilder().addBuilder(index,
						space.marquardt.protobuf.Demo.Student.PhoneNumber.getDefaultInstance());
			}

			/**
			 * <code>repeated .space.marquardt.Student.PhoneNumber phone = 5;</code>
			 */
			public java.util.List<space.marquardt.protobuf.Demo.Student.PhoneNumber.Builder> getPhoneBuilderList() {
				return this.getPhoneFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilderV3<space.marquardt.protobuf.Demo.Student.PhoneNumber, space.marquardt.protobuf.Demo.Student.PhoneNumber.Builder, space.marquardt.protobuf.Demo.Student.PhoneNumberOrBuilder> getPhoneFieldBuilder() {
				if (this.phoneBuilder_ == null) {
					this.phoneBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<>(this.phone_,
							((this.bitField0_ & 0x00000010) == 0x00000010), this.getParentForChildren(),
							this.isClean());
					this.phone_ = null;
				}
				return this.phoneBuilder_;
			}

			@Override
			public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return this;
			}

			@Override
			public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
				return this;
			}

			// @@protoc_insertion_point(builder_scope:space.marquardt.Student)
		}

		// @@protoc_insertion_point(class_scope:space.marquardt.Student)
		private static final space.marquardt.protobuf.Demo.Student DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new space.marquardt.protobuf.Demo.Student();
		}

		public static space.marquardt.protobuf.Demo.Student getDefaultInstance() {
			return Student.DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<Student> PARSER = new com.google.protobuf.AbstractParser<Student>() {
			@Override
			public Student parsePartialFrom(final com.google.protobuf.CodedInputStream input,
					final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
							throws com.google.protobuf.InvalidProtocolBufferException {
				return new Student(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<Student> parser() {
			return Student.PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<Student> getParserForType() {
			return Student.PARSER;
		}

		@Override
		public space.marquardt.protobuf.Demo.Student getDefaultInstanceForType() {
			return Student.DEFAULT_INSTANCE;
		}

	}

	private static final com.google.protobuf.Descriptors.Descriptor internal_static_space_marquardt_Course_descriptor;
	private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_space_marquardt_Course_fieldAccessorTable;
	private static final com.google.protobuf.Descriptors.Descriptor internal_static_space_marquardt_Student_descriptor;
	private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_space_marquardt_Student_fieldAccessorTable;
	private static final com.google.protobuf.Descriptors.Descriptor internal_static_space_marquardt_Student_PhoneNumber_descriptor;
	private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_space_marquardt_Student_PhoneNumber_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return Demo.descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		final java.lang.String[] descriptorData = {
				"\n\027resources/message.proto\022\017space.marquar"
						+ "dt\"T\n\006Course\022\n\n\002id\030\001 \001(\005\022\023\n\013course_name\030"
						+ "\002 \001(\t\022)\n\007student\030\003 \003(\0132\030.space.marquardt"
						+ ".Student\"\367\001\n\007Student\022\n\n\002id\030\001 \001(\005\022\022\n\nfirs"
						+ "t_name\030\002 \001(\t\022\021\n\tlast_name\030\003 \001(\t\022\r\n\005email"
						+ "\030\004 \001(\t\0223\n\005phone\030\005 \003(\0132$.space.marquardt."
						+ "Student.PhoneNumber\032O\n\013PhoneNumber\022\016\n\006nu"
						+ "mber\030\001 \001(\t\0220\n\004type\030\002 \001(\0162\".space.marquar"
						+ "dt.Student.PhoneType\"$\n\tPhoneType\022\t\n\005MBI"
						+ "LE\020\000\022\014\n\010LANDLINE\020\001B \n\030space.marquardt.pr",
		"otobufB\004Demob\006proto3" };
		final com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			@Override
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					final com.google.protobuf.Descriptors.FileDescriptor root) {
				Demo.descriptor = root;
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
		internal_static_space_marquardt_Course_descriptor = Demo.getDescriptor().getMessageTypes().get(0);
		internal_static_space_marquardt_Course_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				Demo.internal_static_space_marquardt_Course_descriptor,
				new java.lang.String[] { "Id", "CourseName", "Student", });
		internal_static_space_marquardt_Student_descriptor = Demo.getDescriptor().getMessageTypes().get(1);
		internal_static_space_marquardt_Student_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				Demo.internal_static_space_marquardt_Student_descriptor,
				new java.lang.String[] { "Id", "FirstName", "LastName", "Email", "Phone", });
		internal_static_space_marquardt_Student_PhoneNumber_descriptor = Demo.internal_static_space_marquardt_Student_descriptor
				.getNestedTypes().get(0);
		internal_static_space_marquardt_Student_PhoneNumber_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				Demo.internal_static_space_marquardt_Student_PhoneNumber_descriptor,
				new java.lang.String[] { "Number", "Type", });
	}

	// @@protoc_insertion_point(outer_class_scope)
}
